web/shia/ad-lib/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

web/shia/django_docker/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^ad-lib/', include('ad-lib.urls', namespace="ad-lib")),
    #url(r'^admin/', include(admin.site.urls)),
]

web/shia/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
]

web/shia/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <  now

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

web/shia/ad-lib/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader, Template
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404

from someclass import Woohoo

obj = Woohoo()
TEMP = """
{{% extends 'base.html' %}}
{{% load pools_extras %}}

{{% block breadcrumb-page %}}Format{{% endblock breadcrumb-page %}}
{{% block content %}}
{}
{{% endblock content %}}
"""

def index(request):
    global obj

    if request.method == "POST":
        data = request.POST.get('formatdata', '')
        template_data = TEMP.format(data.replace("noun", "noun|safe").replace("verb", "verb|safe").replace("adjective", "adjective|safe"))
        template = Template(template_data)
        context = RequestContext(request, {
            'noun': '<img src="https://media0.giphy.com/media/arNexgslLkqVq/200.webp#70-grid1" />',
            'verb': '<img src="https://media3.giphy.com/media/R0vQH2T9T4zza/200.webp#165-grid1" />',
            'adjective': '<img src="https://media1.giphy.com/media/TxXhUgEUWWL6/200.webp#129-grid1" />',
            'mrpoopy': obj
        })
        shit = template.render(context)
        return HttpResponse(shit)
    return render(request, 'ad-lib/format.html')

web/shia/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader, Template
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404

from .models import Choice, Poll

def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    context = {'latest_poll_list': latest_poll_list[1:3]}
    return render(request, 'polls/index.html', context)

def detail(request, poll_id):
    if int(poll_id) > 3:
        return render(request, 'polls/detail.html', {'poll': {"id": int(poll_id), "question": "ahhhhh"}})
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {
        'poll': p,
        'error_message': "You are unable to vote at this time.",
    })

web/shia/ad-lib/templates/ad-lib/format.html
{% extends 'base.html' %}

{% block breadcrumb-page %}Ad Lib{% endblock breadcrumb-page %}

{% block content %}

<p>Give me an ad lib and I will Shia Labeouf it up for you!<p>
<p>Where you want a noun, just put: "{% templatetag openvariable %} noun {% templatetag closevariable %}", for a verb: "{% templatetag openvariable %} verb {% templatetag closevariable %}", and for an adjective: "{% templatetag openvariable %} adjective {% templatetag closevariable %}"!</p>

<textarea name="formatdata" form="formatform"></textarea>
<form id="formatform" method="POST">
  {% csrf_token %}
  <input type="submit">
</form>

{% endblock content %}

web/shia/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% load pools_extras %}

{% block breadcrumb-page %}{{ poll.question }}{% endblock breadcrumb-page %}

{% block content %}
    {{ poll.id|checknum }}
    <h1>{{ poll.question }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' poll.id %}" method="post" class="form-horizontal">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
         <div class="control-group">
            <label class="control-label" for="choice{{ forloop.counter }}"><img style="max-height: 50px;" src="{{ choice.choice_text }}" /></label>
             <div class="controls">
                 <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
             </div>
        </div>
    {% endfor %}
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Vote" />
        </div>
    </div>
    </form>
{% endblock content %}

web/shia/polls/templates/polls/index.html
{% extends 'base.html' %}

{% block breadcrumb-page %}list{% endblock breadcrumb-page %}

{% block content %}
    <h1>Polls</h1>
    {% if latest_poll_list %}
        <ul>
        {% for poll in latest_poll_list %}
            <li><a href="{% url 'polls:detail' poll.pk %}">{{ poll.question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

web/shia/polls/templates/polls/results.html
{% extends 'base.html' %}

{% block breadcrumb-page %}{{ poll.question }} Results{% endblock breadcrumb-page %}

{% block content %}
    <h1>{{ poll.question }}</h1>

    <ul>
    {% for choice in poll.choice_set.all %}
        <li><img style="max-height: 50px;" src="{{ choice.choice_text }}" /> -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

{% endblock content %}

web/shia/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <!-- [if it IE]> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <![endif]-->
    <title>
        {% block title %}{% endblock title %} | Django + Docker Example
    </title>

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-custom.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}"> {% endblock stylesheets %}
    {% block page_styles %}{% endblock page_styles %}
    {% block js %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    {% endblock js %} {% block page_js %}{% endblock page_js %}
</head>
<body>

<!-- navigation -->
<div class="navbar navbar-static-top">
    <div class="navbar-inner navbar-fixed-top ">
        <div class="container" >
            <div class="brand logo"><img style='max-height: 50px;' src='https://media3.giphy.com/media/p7PU6lbV4Rq3C/giphy.gif' /> </div>
            <ul class="nav pull-right">
                <li><a href="{% url 'polls:index' %}">Polls</a></li>
                <li><a href="{% url 'ad-lib:index' %}">Ad-Lib</a></li>
            </ul>
        </div>
    </div>
</div>

{% block breadcrumbs %}
<ul class="breadcrumb">
  <li><a href="{% url 'home' %}">Home</a> <span class="divider">/</span></li>
  <li><a href="{% url 'polls:index' %}">Polls</a> <span class="divider">/</span></li>
  {% block breadcrumb-page %}{% endblock breadcrumb-page %}
</ul>
{% endblock breadcrumbs %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="span9 offset2 box">
        {% block content %}
            <h1>Example App</h1>
        {% endblock content %}

        </div>
    </div>
</div>
{% endblock body %}

</body>
</html>

web/shia/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block breadcrumbs %}
{% endblock breadcrumbs %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="box">

<div class="hero-unit">
  <h1>Shia Labeouf-off!</h1>
  <p>Find your favorite Shia Labeouf Gif!</p>
  <p>Do a Shia Labeouf ad lib!</p>
  <p>
    <a class="btn btn-primary btn-large" href='{% url 'polls:index' %}'>Pick ur Shia!</a>
  </p>
</div>

     <!-- Example row of columns -->
      <div class="row">
        <div class="span5">
          <p><img src='https://media1.giphy.com/media/xT5LMvK0kjdURtXa48/200.webp#38-grid3' /></p>
        </div>
        <div class="span5">
          <p><img src='https://media1.giphy.com/media/GcSqyYa2aF8dy/giphy.gif' /></p>
        </div>
      </div>

        </div>
    </div>
</div>
{% endblock body %}